services:
  open-webui:
      ports:
          - 7861:8080
      environment:
          - OPENAI_API_KEY=foo
          - OLLAMA_API_BASE_URL=http://ollama:11434
          - WEBUI_AUTH=false
      volumes:
          - ./open-webui:/app/backend/data
      container_name: open-webui
      image: ghcr.io/open-webui/open-webui:main
      restart: always
      extra_hosts:
        - "host.docker.internal:host-gateway"